# _config.yml

# define custom collections
collections:
  objects:              # content lives in _objects/
    output: true        # generate HTML for each item
    permalink: /objects/:name/
  diagrams:             # content lives in _diagrams/
    output: true
    permalink: /diagrams/:name/

# exclude rules
# by default, include everything
# if running in production (JEKYLL_ENV=production),
# then exclude all files under _diagrams/
exclude:
{% if jekyll.environment == "production" %}
  - _diagrams/**
{% endif %}

# ---- usage notes ----
# Development (default environment):
#   bundle exec jekyll serve
#
# Production build (excludes _diagrams/**):
#   JEKYLL_ENV=production bundle exec jekyll build
#
# Production server run (also excludes _diagrams/**):
#   JEKYLL_ENV=production bundle exec jekyll serve

