# _config_prod.yml

# --------------------------------------------------
# Production overrides
# --------------------------------------------------
# Exclude the entire _sandbox/ collection in production.
exclude:
  - _sandbox/**

